variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test
  - deploy

docker-build:
  # Use the official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  # Default branch leaves tag empty (= latest tag)
  # All other branches are tagged with the escaped branch name (commit ref slug)
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=":latest"
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build --pull -t "${CI_REGISTRY_IMAGE}${tag}" .
    - |
      if [[ -z ${CI_COMMIT_TAG+x} ]]; then
        docker tag "${CI_PROJECT_NAME}${tag}" "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
      fi
    - docker push --all-tags
  # Run this job in a branch where a Dockerfile exists
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile

MR:
  image: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' 
  script:
    - (cd examples; bash build-examples.sh)
  artifacts:
    paths:
      - examples

pages:
  image: "$CI_REGISTRY_IMAGE:latest"
  stage: deploy
  script:
    - (cd examples; bash build-examples.sh)
    - pandoc --toc --template=GitHub.html5 ./examples/index.md -o ./examples/index.html
    - mv examples public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
