image: condaforge/mambaforge:4.11.0-0

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get update -qq && apt-get install fonts-noto-cjk -qqy
  - mamba env update -n base --file environment.yml
  # - source activate tectonic
  - (cd examples; bash build-examples.sh)

tests:
  script:
  - echo "Build complete!"
  except:
  - main

pages:
  script:
  - pandoc --toc --template=GitHub.html5 ./examples/index.md -o ./examples/index.html
  - mv examples public
  artifacts:
    paths:
    - public
  only:
  - main
