include:
  - project: 'sosiristseng/gitlab-templates'
    file: '/mambaforge.gitlab-ci.yml'

variables:
  GIT_SUBMODULE_STRATEGY: recursive

tests:
  script:
    - apt-get update -qq && apt-get install fonts-noto-cjk -qqy
    - (cd examples; bash build-examples.sh)
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  artifacts:
    paths:
      - examples

pages:
  script:
    - apt-get update -qq && apt-get install fonts-noto-cjk -qqy
    - (cd examples; bash build-examples.sh)
    - pandoc --toc --template=GitHub.html5 ./examples/index.md -o ./examples/index.html
    - mv examples public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
