image: mambaorg/micromamba:0.19.1

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - su - -c "apt-get update -qq && apt-get install fonts-noto-cjk -qqy"
  - micromamba install -y -f environment.yml -n base
  # - source activate tectonic
  - (cd examples; bash build-examples.sh)

tests:
  script:
  - echo "Build complete!"
  except:
  - main

pages:
  script:
  - pandoc --toc --template=GitHub.html5 ./examples/index.md -o ./examples/index.html
  - mv examples public
  artifacts:
    paths:
    - public
  only:
  - main
