image: condaforge/mambaforge:4.11.0

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CONDA_PKGS_DIRS: "${CI_PROJECT_DIR}/.cache/conda/pkgs"

cache:
  - key:
      files:
        - environment.yml
    paths:
      - .env/
      - .cache/conda/pkgs

before_script:
  - apt-get update -qq && apt-get install fonts-noto-cjk -qqy
  - mamba env update --prefix ./.env --file environment.yml --prune
  - source activate ./.env
  - (cd examples; bash build-examples.sh)
  - pandoc --toc --template=GitHub.html5 ./examples/index.md -o ./examples/index.html

tests:
  script:
    - echo "Build complete!"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

pages:
  script:
    - mv examples public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
