image: condaforge/mambaforge:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - mamba env create -f environment.yml
  - source activate tectonic
  - apt-get update -qq && apt-get install fonts-noto-cjk -y
  - cd examples && bash build-examples.sh && cd ..

tests:
  script:
  - echo "Build complete!"
  except:
  - main

pages:
  script:
  - pandoc --toc --template=GitHub.html5 ./examples/index.md -o ./examples/index.html
  - mv examples public
  artifacts:
    paths:
    - public
  only:
  - main
