name: Build Example PDF files

on: [push, pull_request]

env:
  PDC_VER: "2.17.1.1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup pandoc
        run: |
          echo "Installing pandoc version ${PDC_VER}"
          wget -qO- https://github.com/jgm/pandoc/releases/download/${PDC_VER}/pandoc-${PDC_VER}-linux-amd64.tar.gz | sudo tar xvzf - --strip-components 1 -C /usr/local/
      - name: Tectonic Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
          restore-keys: |
            ${{ runner.os }}-tectonic-
      - uses: wtfjoke/setup-tectonic@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tectonic-version: "0.8.0"
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: "pip"
      - run: pip install -r requirements.txt
      - name: Setup fonts and image convertion tool
        run: sudo apt-get update -qq && sudo apt-get install fonts-noto-cjk poppler-utils -qqy
      - name: Build pdf files
        run: cd examples && bash build-examples.sh && cd ..
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-files
          path: |
            examples/*/document.pdf
            examples/*/preview.png
      - name: Build index page
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          pandoc --toc --template=GitHub.html5 ./examples/index.md -o ./examples/index.html
      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: false
          publish_dir: ./examples
